### ISSUE TITLE
Issue with example

### ISSUE THREAD

**Issue by straris** [tacoss/dayguard#1]
Running the example will result in the following error ```require(...).use is not a function```

**Comment by pateketrueke** [comment]
Sorry for the lag, effectively this was an issue... so, I updated the codebase and fixed the API.

I'm not aware if Nightwatch has now an API for registering plugins, I'll do such research later...

Meanwhile I think you can check the example in the README. ;-)

Thanks for your feedback!

**Comment by straris** [comment]
@pateketrueke thank you for fixing it. Not relevant to the ticket but I intended to use dayguard to take screenshots of elements that are not in the viewport, but it looks like an attempt to take a screenshot of an element that is further down in the page will produce an empty screenshot.

**Comment by straris** [comment]
saying that, solved the above by using `.getLocationInView()` before the screenshot :)

**Comment by straris** [comment]
thank you for the quick resolution btw
