### ISSUE TITLE
Add customName to visualChangesOf

### ISSUE THREAD

**Issue by kraftner** [tacoss/dayguard#5]
Currently you can't have a custom name when using `visualChangesOf`which is somewhat problematic when using the same selector in different tests inside the same test group.

Current use cases are e.g.:
- testing a whole form in invalid and valid state
- testing the layout of an element in various resolutions (think media queries...)

I think implementation shouldn't be difficult and I'm willing to prepare a PR, just checking if you have any objections to this before digging in.

**Comment by pateketrueke** [comment]
So much thanks for your feedback!

I guess receiving the `customName` [here](https://github.com/tacoss/dayguard/blob/master/lib/assertions/visualChangesOf.js#L3) and passing it down [here](https://github.com/tacoss/dayguard/blob/master/lib/assertions/visualChangesOf.js#L28-L29) should be enough right?

I'm sure the provided commands already accept a `customName` parameter, but I'm not sure how much more work is needed... 🤔 

Go ahead, thanks for you pointing this out.

**Comment by kraftner** [comment]
Yeah sounds reasonable, I hadn't really looked at the code yet.

Will try to come up with something PR-worthy. :smile:

**Comment by kraftner** [comment]
Okay so this seems to work. The only thing I am wondering about is the function signature.
We either brake backwards compatibility by making it consistent with the other functions

    visualChangesOf(selector, customName, threshold)

Or just add `customName` at the end which doesn't mess with existing tests.

    visualChangesOf(selector, threshold, customName)

As dayguard is still pretty young I'd say make it version 0.3 and have a nice and consistent function signature, so option 1. What do you think?

**Comment by kraftner** [comment]
Okay I've gone ahead and made a PR. If you feel like you want the other function signature let me know so I can update the PR.

**Comment by pateketrueke** [comment]
Yeah, totally agreed.

The first signature is more consistent so far.

Giving the ability to fallback if the second parameter is intended to be `threshold` is preferred, what do you think?

```js
if (typeof customName === 'number') {
  threshold = customName;
  customName = undefined;
}
```

This way we can use `visualChangesOf(selector, customName)` or `visualChangesOf(selector, threshold)` cleanly (the latter suffer from the original issue anyway so you must prepend a custom name, etc).

Of course the arguments are not expected to be exchangeable, so `visualChangesOf(selector, threshold, customName)` should not be allowed.

**Comment by kraftner** [comment]
Good idea, I updated the PR.
